export const LANGUAGE_ALIASES: Record<string, string> = {
  asm: "asm6502",
  bat: "batch",
  cbl: "cobol",
  clj: "clojure",
  coffee: "coffeescript",
  cpp: "cpp",
  cs: "csharp",
  ex: "elixir",
  f90: "fortran",
  hs: "haskell",
  jl: "julia",
  js: "javascript",
  kt: "kotlin",
  md: "markdown",
  ml: "ocaml",
  mm: "objective-c",
  pl: "perl",
  pm: "perl",
  ps1: "powershell",
  py: "python",
  rb: "ruby",
  rs: "rust",
  sh: "bash",
  tex: "latex",
  ts: "typescript",
  yaml: "yml"
};
